title = "reading minds or recording information from inner voice is not ok. all signals produced by my body should be considered illegal and against my will. any derivatives in product or entertainment should be looked at as infringing on my privacy as i have been and am attemping to record, work on and keep such information to myself. "
baseURL = "/"
tags = ["portfolio", "data", "analytics", "quantitative"]
languageCode = "en-US"
config = "config.toml"
publishDir = "docs"     # added by irJERAD
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-54516992-1"

[Params]
    author = "Jerad Acosta"
    description = "Devoted student of _Data Ninjutsu_"
    logoBig = "/images/DataWordCloud.png"
    logoSmall = "/images/DataWordCloud.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/DataWordCloud.png"
    disqusShortname = "irJERAD"
    twitter = "irJERAD"
    linkedin = "JeradAcosta"
    github = "irJERAD"
    email = "jsacosta1103@gmail.com"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true

[[menu.main]]
    name = "Thoughts"
    url  = "/#thoughts"
    weight = 4
[[menu.main]]
    name = "Info"
    url  = "/#info"
    weight = 2
[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 3
[[menu.main]]
    name = "Story Time"
    url  = "/#storytime"
    weight = 1
